//
//  test_json.swift
//  说书人普拉斯
//
//  Created by Xuan Tang on 5/21/25.
//

let test_json: [[String: Any]] = [
    ["id": "_meta", "logo": "https://oss.gstonegames.com/data_file/clocktower/upload/1689597955_197011_4546.png", "name": "偷天换日", "townsfolkName": "镇民", "author": ""],
    ["firstNightReminder": "给他展示数字手势来告诉他恶魔与爪牙之间最近的距离。", "otherNightReminder": "", "name": "钟表匠", "otherNight": 0, "setup": false, "reminders": [], "id": "clockmakerbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Clockmaker", "firstNight": 40, "ability": "在你的首个夜晚，你会得知恶魔与爪牙之间最近的距离。（邻座的玩家距离为1）", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/clockmaker.png"],
    ["firstNightReminder": "对小精灵展示一个在场的镇民角色。", "otherNightReminder": "", "name": "小精灵", "otherNight": 0, "setup": false, "reminders": ["疯狂", "获得能力"], "id": "pixiebutton", "edition": "custom", "team": "townsfolk", "name_eng": "Pixie", "firstNight": 29, "ability": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/pixie.png"],
    ["firstNightReminder": "", "otherNightReminder": "让旅店老板选择两名玩家。标记这两名玩家不会死亡，并标记其中一人醉酒。", "name": "旅店老板", "otherNight": 9, "setup": false, "reminders": ["不会死亡", "醉酒"], "id": "innkeeperbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Innkeeper", "firstNight": 0, "ability": "每个夜晚*，你要选择两名玩家：他们当晚不会死亡，但其中一人会醉酒到下个黄昏。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/innkeeper.png"],
    ["firstNightReminder": "", "otherNightReminder": "半兽人指向一名存活玩家：如果那名玩家善良，则立刻死去且今夜不会再有玩家死亡。", "name": "半兽人", "otherNight": 23, "setup": false, "reminders": ["死亡"], "id": "lycanthropebutton", "edition": "custom", "team": "townsfolk", "name_eng": "Lycanthrope", "firstNight": 0, "ability": "每个夜晚*，你要选择一名存活的玩家，如果他是善良的，他死亡，并且当晚不会再有其他玩家死亡。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/lycanthrope.png"],
    ["firstNightReminder": "让占卜师选择两名玩家。如果其中有恶魔或“干扰项”，点头示意，否则摇头。", "otherNightReminder": "让占卜师选择两名玩家。如果其中有恶魔或“干扰项”，点头示意，否则摇头。", "name": "占卜师", "otherNight": 54, "setup": false, "reminders": ["干扰项"], "id": "fortune_tellerbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Fortune Teller", "firstNight": 37, "ability": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/fortune_teller.png"],
    ["firstNightReminder": "给他展示数字手势来告诉他与他邻近的存活玩家有几人是邪恶的。", "otherNightReminder": "给他展示数字手势来告诉他与他邻近的存活玩家有几人是邪恶的。", "name": "共情者", "otherNight": 53, "setup": false, "reminders": [], "id": "empathbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Empath", "firstNight": 36, "ability": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/empath.png"],
    ["firstNightReminder": "", "otherNightReminder": "对他点头或摇头示意今天白天是否有爪牙发起过提名。", "name": "城镇公告员", "otherNight": 59, "setup": false, "reminders": ["爪牙未提名", "爪牙已提名"], "id": "town_crierbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Town Crier", "firstNight": 0, "ability": "每个夜晚*，你会得知在今天白天时是否有爪牙发起过提名。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/town_crier.png"],
    ["firstNightReminder": "女裁缝可以选择除自己以外的两名玩家。如果她这么做了，对她点头或摇头示意这两名玩家是否为同一阵营，随后标记女裁缝失去能力。之后的夜晚无需再唤醒女裁缝。", "otherNightReminder": "女裁缝可以选择除自己以外的两名玩家。如果她这么做了，对她点头或摇头示意这两名玩家是否为同一阵营，随后标记女裁缝失去能力。之后的夜晚无需再唤醒女裁缝。", "name": "女裁缝", "otherNight": 61, "setup": false, "reminders": ["失去能力"], "id": "seamstressbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Seamstress", "firstNight": 42, "ability": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/seamstress.png"],
    ["firstNightReminder": "告诉将军你认为的答案。", "otherNightReminder": "告诉将军你认为的答案。", "name": "将军", "otherNight": 69, "setup": false, "reminders": [], "id": "generalbutton", "edition": "custom", "team": "townsfolk", "name_eng": "General", "firstNight": 49, "ability": "每个夜晚，你会得知说书人认为哪个阵营当前更有优势（善良/邪恶/均势）。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/general.png"],
    ["firstNightReminder": "", "otherNightReminder": "如果守鸦人今晚死亡，唤醒他并让他选择一名玩家。对他展示那名玩家的角色标记。", "name": "守鸦人", "otherNight": 42, "setup": false, "reminders": [], "id": "ravenkeeperbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Ravenkeeper", "firstNight": 0, "ability": "如果你在夜晚死亡，你会被唤醒，然后你要选择一名玩家：你会得知他的角色。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/ravenkeeper.png"],
    ["firstNightReminder": "给他展示数字手势来告诉他在首个夜晚里有多少玩家的角色能力受他人影响而未正常生效。", "otherNightReminder": "给他展示数字手势来告诉他从上个黎明到数学家醒来前有多少玩家的角色能力受他人影响而未正常生效。", "name": "数学家", "otherNight": 71, "setup": false, "reminders": ["未正常生效"], "id": "mathematicianbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Mathematician", "firstNight": 51, "ability": "每个夜晚，你会得知有多少名玩家的能力因为其他角色的能力而未正常生效。(从上个黎明到你被唤醒时）", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/mathematician.png"],
    ["firstNightReminder": "", "otherNightReminder": "", "name": "魔术师", "otherNight": 0, "setup": false, "reminders": [], "id": "magicianbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Magician", "firstNight": 0, "ability": "恶魔会以为你是爪牙。爪牙会以为你是恶魔。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/magician.png"],
    ["firstNightReminder": "", "otherNightReminder": "", "name": "博学者", "otherNight": 0, "setup": false, "reminders": [], "id": "savantbutton", "edition": "custom", "team": "townsfolk", "name_eng": "Savant", "firstNight": 0, "ability": "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/savant.png"],
    ["firstNightReminder": "", "otherNightReminder": "", "name": "酒鬼", "otherNight": 0, "setup": true, "reminders": [], "id": "drunkbutton", "edition": "custom", "remindersGlobal": ["是酒鬼"], "team": "outsider", "name_eng": "Drunk", "firstNight": 0, "ability": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/drunk.png"],
    ["firstNightReminder": "", "otherNightReminder": "", "name": "畸形秀演员", "otherNight": 0, "setup": false, "reminders": [], "id": "mutantbutton", "edition": "custom", "team": "outsider", "name_eng": "Mutant", "firstNight": 0, "ability": "如果你“疯狂”地证明自己是外来者，你可能被处决。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/mutant.png"],
    ["firstNightReminder": "", "otherNightReminder": "", "name": "莽夫", "otherNight": 0, "setup": false, "reminders": ["醉酒"], "id": "goonbutton", "edition": "custom", "team": "outsider", "name_eng": "Goon", "firstNight": 0, "ability": "每个夜晚，首个使用其自身能力选择了你的玩家会醉酒直到下个黄昏。你会转变为他的阵营。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/goon.png"],
    ["firstNightReminder": "如果有七名或更多玩家，唤醒疯子：展示“他们是你的爪牙”信息标记。指向任意对应数量的玩家。展示“这些角色不在场”信息标记。展示三个善良角色。让疯子重新入睡。唤醒恶魔。展示“你是”信息标记和恶魔角色标记。展示“这名玩家是”信息标记和疯子角色标记，然后指向疯子玩家。", "otherNightReminder": "做任何需要做的事情来模拟一位恶魔的行动。让疯子重新入睡。唤醒恶魔。对恶魔展示疯子角色标记，并指向疯子玩家，随后是疯子的攻击目标。", "name": "疯子", "otherNight": 21, "setup": false, "reminders": [], "id": "lunaticbutton", "edition": "custom", "remindersGlobal": ["是疯子", "被选择"], "team": "outsider", "name_eng": "Lunatic", "firstNight": 7, "ability": "你以为你是一个恶魔，但其实你不是。恶魔知道你是疯子以及你在每个夜晚选择了哪些玩家。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/lunatic.png"],
    ["firstNightReminder": "", "otherNightReminder": "", "name": "陌客", "otherNight": 0, "setup": false, "reminders": [], "id": "reclusebutton", "edition": "custom", "team": "outsider", "name_eng": "Recluse", "firstNight": 0, "ability": "你可能会被当作邪恶阵营、爪牙角色或恶魔角色，即使你已死亡。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/recluse.png"],
    ["firstNightReminder": "让投毒者选择一名玩家。标记那名玩家中毒。", "otherNightReminder": "让投毒者选择一名玩家。标记那名玩家中毒。", "name": "投毒者", "otherNight": 8, "setup": false, "reminders": ["中毒"], "id": "poisonerbutton", "edition": "custom", "team": "minion", "name_eng": "Poisoner", "firstNight": 17, "ability": "每个夜晚，你要选择一名玩家：他在当晚和明天白天中毒。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/poisoner.png"],
    ["firstNightReminder": "让洗脑师选择一名玩家和一个善良角色。标记那名玩家疯狂。让洗脑师重新入睡。唤醒洗脑师的目标。对这名玩家展示“该角色的能力对你生效”信息标记，洗脑师角色标记，该玩家需要疯狂证明的角色标记。", "otherNightReminder": "让洗脑师选择一名玩家和一个善良角色。标记那名玩家疯狂。让洗脑师重新入睡。唤醒洗脑师的目标。对这名玩家展示“该角色的能力对你生效”信息标记，洗脑师角色标记，该玩家需要疯狂证明的角色标记。", "name": "洗脑师", "otherNight": 16, "setup": false, "reminders": ["疯狂"], "id": "cerenovusbutton", "edition": "custom", "team": "minion", "name_eng": "Cerenovus", "firstNight": 25, "ability": "每个夜晚，你要选择一名玩家和一个善良角色。他明天白天和夜晚需要“疯狂”地证明自己是这个角色，不然他可能被处决。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/cerenovus.png"],
    ["firstNightReminder": "", "otherNightReminder": "如果红唇女郎今天变成了小恶魔，对她展示“你是”信息标记，和小恶魔角色标记。", "name": "红唇女郎", "otherNight": 20, "setup": false, "reminders": [], "id": "scarlet_womanbutton", "edition": "custom", "remindersGlobal": ["是恶魔"], "team": "minion", "name_eng": "Scarlet Woman", "firstNight": 0, "ability": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/scarlet_woman.png"],
    ["firstNightReminder": "让女巫选择一名玩家。标记那名玩家被诅咒。", "otherNightReminder": "让女巫选择一名玩家。标记那名玩家被诅咒。", "name": "女巫", "otherNight": 15, "setup": false, "reminders": ["被诅咒"], "id": "witchbutton", "edition": "custom", "team": "minion", "name_eng": "Witch", "firstNight": 24, "ability": "每个夜晚，你要选择一名玩家：如果他明天白天发起提名，他死亡。如果只有三名存活的玩家，你失去此能力。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/witch.png"],
    ["firstNightReminder": "", "otherNightReminder": "让小恶魔选择一名玩家。标记那名玩家死亡。如果小恶魔选择了自己：用一个备用的小恶魔标记替换一个存活的爪牙角色标记。让原来的小恶魔重新入睡。唤醒新的小恶魔。对他展示“你是”信息标记，和小恶魔角色标记。", "name": "小恶魔", "otherNight": 24, "setup": false, "reminders": ["死亡"], "id": "impbutton", "edition": "custom", "team": "demon", "name_eng": "Imp", "firstNight": 0, "ability": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式自杀，一名爪牙会变成小恶魔。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/imp.png"],
    ["firstNightReminder": "", "otherNightReminder": "让方古选择一名玩家。标记那名玩家死亡。如果他选择了外来者，且“首次”标记未放置在魔典中：用备用的方古角色标记替换那名外来者的角色标记。让方古重新入睡。唤醒方古的目标玩家。对该玩家展示“你是”信息标记和方古角色标记，并用拇指向下代表他阵营变为邪恶。将“首次”标记放置在魔典中。标记原本的方古玩家死亡，且他选择的玩家不会被标记为死亡。", "name": "方古", "otherNight": 29, "setup": true, "reminders": ["死亡"], "id": "fang_gubutton", "edition": "custom", "remindersGlobal": ["限一次"], "team": "demon", "name_eng": "Fang Gu", "firstNight": 0, "ability": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/fang_gu.png"],
    ["firstNightReminder": "让普卡选择一名玩家。标记那名玩家中毒。", "otherNightReminder": "让普卡选择一名玩家。标记那名玩家中毒。【圆】上一个因普卡中毒的玩家死亡，随后恢复健康。", "name": "普卡", "otherNight": 26, "setup": false, "reminders": ["死亡", "中毒"], "id": "pukkabutton", "edition": "custom", "team": "demon", "name_eng": "Pukka", "firstNight": 28, "ability": "每个夜晚，你要选择一名玩家：他中毒。上个因你的能力中毒的玩家会死亡并恢复健康。", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/pukka.png"],
    ["ability": "使用灯神的相克规则。所有玩家都会知道其内容。", "image": "https://oss.gstonegames.com/data_file/clocktower/role_icon/djinn.png", "edition": "custom", "flavor": "", "id": "djinnbutton", "firstNightReminder": "", "otherNightReminder": "", "name": "灯神", "otherNight": 0, "setup": 0, "reminders": [], "remindersGlobal": [], "team": "fabled", "firstNight": 0]
]


let test_json2: [[String: Any]] = [
    ["id": "_meta", "name": "7席谜案录-TrashWarlock", "logo": "https://img.picui.cn/free/2025/03/19/67da4690a63e7.png", "author": "TrashWarlock", "description": "7席谜案录", "townsfolkName": "镇民", "outsidersName": "外来者", "minionsName": "爪牙", "demonsName": "恶魔", "townsfolk": "镇民", "outsider": "外来者", "minion": "爪牙", "demon": "恶魔", "a jinxedName": "相克", "a jinxed": "相克", "state": [["stateName": "第七把交椅", "stateDescription": "在游戏开始时，第七个座位是空的，但正常发角色。每局游戏限一次，说书人可以代表第七个座位发言，并可以参与提名。说书人决定在扮演第七个座位的角色时，该如何行动。"]], "status": [["name": "第七把交椅", "skill": "在游戏开始时，第七个座位是空的，但正常发角色。每局游戏限一次，说书人可以代表第七个座位发言，并可以参与提名。说书人决定在扮演第七个座位的角色时，该如何行动。"]]],
    ["id": "35addde2-e27a-4de2-9a9e-df0e78364717", "image": "https://oss.gstonegames.com/data_file/clocktower/upload/202304/c_1310810162861_4da173fa.jpg", "edition": "custom", "name": "私货商人", "ability": "这个剧本包含有自制角色或自制规则。", "team": "fabled", "firstNight": 0, "otherNight": 0],
    ["id": "xiyifufuchuyinweilaidefufu111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/washerwoman.png", "edition": "custom", "name": "洗衣妇", "ability": "在你的首个夜晚，你会得知两名玩家和一个镇民角色：这两名玩家之一是该角色。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 35, "otherNight": 0, "firstNightReminder": "唤醒洗衣妇，对她指向两名玩家，并展示一个镇民角色标记。这两名玩家其中之一是这个镇民。", "otherNightReminder": "", "reminders": ["镇民", "错误"], "setup": false],
    ["id": "daerduotutu111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/librarian.png", "edition": "custom", "name": "图书管理员", "ability": "在你的首个夜晚，你会得知两名玩家和一个外来者角色：这两名玩家之一是该角色（或者你会得知没有外来者在场）。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 36, "otherNight": 0, "firstNightReminder": "唤醒图书管理员，对他指向两名玩家，并展示一个外来者角色标记。这两名玩家其中之一是这个外来者。", "otherNightReminder": "", "reminders": ["外来者", "错误"], "setup": false],
    ["id": "jingcaisanxuanyi111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/noble.png", "edition": "custom", "name": "贵族", "ability": "在你的首个夜晚，你会得知三名玩家：其中有且只有一名玩家是邪恶的。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 49, "otherNight": 0, "firstNightReminder": "唤醒贵族，对他指向三名玩家。这三名玩家中有且仅有一名是邪恶玩家。", "otherNightReminder": "", "reminders": ["被得知"], "setup": false],
    ["id": "mofashuijingqiu111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/fortune_teller.png", "edition": "custom", "name": "占卜师", "ability": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 40, "otherNight": 81, "firstNightReminder": "唤醒占卜师，让他选择两名玩家。以点头或摇头告知他是否选中了恶魔。", "otherNightReminder": "唤醒占卜师，让他选择两名玩家。以点头或摇头告知他是否选中了恶魔。", "reminders": ["干扰项"], "setup": false],
    ["id": "rangwokangkang111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/dreamer.png", "edition": "custom", "name": "筑梦师", "ability": "每个夜晚，你要选择除你及旅行者以外的一名玩家：你会得知一个善良角色和一个邪恶角色，该玩家是其中一个角色。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 45, "otherNight": 84, "firstNightReminder": "唤醒筑梦师，让他选择一名除自己以外的非旅行者玩家。对他展示一善一恶两个角色标记。", "otherNightReminder": "唤醒筑梦师，让他选择一名除自己以外的非旅行者玩家。对他展示一善一恶两个角色标记。", "reminders": [], "setup": false],
    ["id": "zhuijidelaoda111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/balloonist.png", "edition": "custom", "name": "气球驾驶员", "ability": "每个夜晚，你会得知一名与上个夜晚得知的玩家角色类型不同的玩家。[+0~1外来者]", "team": "townsfolk", "sch_team": "镇民", "firstNight": 50, "otherNight": 90, "firstNightReminder": "唤醒气球驾驶员，对他指向一名玩家。", "otherNightReminder": "唤醒气球驾驶员，对他指向一名玩家，这名玩家与之前气球驾驶员上一个夜晚得知过的玩家属于不同的角色类型。", "reminders": ["得知"], "setup": true],
    ["id": "lingluowawa111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/seamstress.png", "edition": "custom", "name": "女裁缝", "ability": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 46, "otherNight": 88, "firstNightReminder": "唤醒女裁缝，她可以摇头不使用能力，或选择除自己以外的两名玩家。以点头或摇头告知她选择的玩家是否为同一阵营。", "otherNightReminder": "如果女裁缝未曾使用能力，唤醒女裁缝，她可以摇头不使用能力，或选择除自己以外的两名玩家。以点头或摇头告知她选择的玩家是否为同一阵营。", "reminders": ["失去能力"], "setup": false],
    ["id": "diaoshangyizhengtiandeyu111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/fisherman.png", "edition": "custom", "name": "渔夫", "ability": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 0, "otherNight": 0, "firstNightReminder": "", "otherNightReminder": "", "reminders": ["失去能力"], "setup": false],
    ["id": "tiepigu111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/virgin.png", "edition": "custom", "name": "贞洁者", "ability": "当你首次被提名时，如果提名你的玩家是镇民，他立刻被处决。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 0, "otherNight": 0, "firstNightReminder": "", "otherNightReminder": "", "reminders": ["失去能力"], "setup": false],
    ["id": "liuqian111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/magician.png", "edition": "custom", "name": "魔术师", "ability": "恶魔会以为你是爪牙。爪牙会以为你是恶魔。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 3.6, "otherNight": 0, "firstNightReminder": "如果魔术师在场，则需要对爪牙信息环节和恶魔信息环节的相关内容进行调整。", "otherNightReminder": "", "reminders": [], "setup": false],
    ["id": "sb111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/soldier.png", "edition": "custom", "name": "士兵", "ability": "恶魔的负面能力对你无效。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 0, "otherNight": 0, "firstNightReminder": "", "otherNightReminder": "", "reminders": [], "setup": false],
    ["id": "zz111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/mayor.png", "edition": "custom", "name": "镇长", "ability": "如果只有三名玩家存活且白天没有人被处决，你的阵营获胜。如果你在夜晚死亡，可能会有一名其他玩家代替你死亡。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 0, "otherNight": 0, "firstNightReminder": "", "otherNightReminder": "", "reminders": [], "setup": false],
    ["id": "wangzherongyao111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/farmer.png", "edition": "custom", "name": "农夫", "ability": "当你在夜晚死亡时，一名存活的善良玩家会变成农夫。", "team": "townsfolk", "sch_team": "镇民", "firstNight": 0, "otherNight": 74, "firstNightReminder": "", "otherNightReminder": "如果农夫死于夜晚，唤醒一名存活的善良玩家告知他角色变化。", "reminders": [], "setup": false],
    ["id": "zhegeshimonk111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/recluse.png", "edition": "custom", "name": "陌客", "ability": "你可能会被当作邪恶阵营、爪牙角色或恶魔角色，即使你已死亡。", "team": "outsider", "sch_team": "外来者", "firstNight": 0, "otherNight": 0, "firstNightReminder": "", "otherNightReminder": "", "reminders": [], "setup": false],
    ["id": "woheduolema111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/drunk.png", "edition": "custom", "name": "酒鬼", "ability": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "team": "outsider", "sch_team": "外来者", "firstNight": 0, "otherNight": 0, "firstNightReminder": "", "otherNightReminder": "", "reminders": [], "remindersGlobal": ["是酒鬼"], "setup": true],
    ["id": "shuiganshawo111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/saint.png", "edition": "custom", "name": "圣徒", "ability": "如果你死于处决，你的阵营落败。", "team": "outsider", "sch_team": "外来者", "firstNight": 0, "otherNight": 0, "firstNightReminder": "", "otherNightReminder": "", "reminders": [], "setup": false],
    ["id": "biezaizhelifadian111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/barber.png", "edition": "custom", "name": "理发师", "ability": "如果你死亡，在当晚恶魔可以选择两名玩家（不能选择其他恶魔）交换角色。", "team": "outsider", "sch_team": "外来者", "firstNight": 0, "otherNight": 67, "firstNightReminder": "", "otherNightReminder": "如果理发师死于白天，唤醒恶魔让他决定是否使用理发师的能力。如果理发师死于夜晚，（如果让除攻击理发师以外的恶魔进行选择则需要等当前恶魔入睡后）让一名恶魔决定是否使用理发师的能力。", "reminders": ["今晚理发"], "setup": false],
    ["id": "bushiwo111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/damsel.png", "edition": "custom", "name": "落难少女", "ability": "所有爪牙都知道落难少女在场。每局游戏限一次，任意爪牙可以公开猜测你是落难少女，如果猜对，你的阵营落败。", "team": "outsider", "sch_team": "外来者", "firstNight": 5.1, "otherNight": 0, "firstNightReminder": "如果落难少女在场，对爪牙展示落难少女角色标记。", "otherNightReminder": "0", "reminders": ["已被猜测"], "setup": false],
    ["id": "zhadaobaozhala111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/boomdandy.png", "edition": "custom", "name": "炸弹人", "ability": "如果你被处决，除三名玩家以外的其他所有玩家均会死亡。倒数十声后，被最多玩家手指指着的玩家死亡。", "team": "minion", "sch_team": "爪牙", "firstNight": 0, "otherNight": 0, "firstNightReminder": "", "otherNightReminder": "", "reminders": [], "setup": false],
    ["id": "hongchunnvlangaaaaaaaa111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/scarlet_woman.png", "edition": "custom", "name": "红唇女郎", "ability": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "team": "minion", "sch_team": "爪牙", "firstNight": 0, "otherNight": 26, "otherNightReminder": "如果红唇女郎的能力曾被触发，唤醒她并告知她变成了哪个恶魔角色。", "reminders": ["是恶魔"]],
    ["id": "lllllllllllllllllllllll11111111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/pit-hag.png", "edition": "custom", "name": "麻脸巫婆", "ability": "每个夜晚*，你要选择一名玩家和一个角色，如果该角色不在场，他变成该角色。如果因此创造了一个恶魔，当晚的死亡由说书人决定。", "team": "minion", "sch_team": "爪牙", "firstNight": 0, "otherNight": 8, "firstNightReminder": "", "otherNightReminder": "唤醒麻脸巫婆，让她选择一名玩家和角色列表上的一个角色。如果该角色不在场，则在麻脸巫婆入睡后通知该玩家角色变化。根据实际情况，可以将相关通知合并，例如玩家变成了恶魔，则在恶魔行动时一并唤醒，通知角色变化并让他执行相应行动。", "reminders": [], "setup": false],
    ["id": "weishenmebushilianjinshushi111", "image": "https://clocktower-wiki.gstonegames.com/images/f/f1/Boffin.png", "edition": "custom", "name": "科学怪人", "ability": "恶魔拥有一个不在场的善良角色的能力，即使他醉酒或中毒。你和他都知道他获得了什么能力。", "team": "minion", "sch_team": "爪牙", "firstNight": 1.45, "otherNight": 0, "firstNightReminder": "（分别或同时）唤醒科学怪人和恶魔，通知他们恶魔因为科学怪人而获得的善良角色的能力。", "otherNightReminder": "", "reminders": [], "setup": true],
    ["id": "wangguuuuuuuu111111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/vigormortis.png", "edition": "custom", "name": "亡骨魔", "ability": "每个夜晚*，你要选择一名玩家：他死亡。被你杀死的爪牙保留他的能力，且与他邻近的两名镇民之一中毒。[-1外来者]", "team": "demon", "sch_team": "恶魔", "firstNight": 0, "otherNight": 40, "firstNightReminder": "", "otherNightReminder": "唤醒亡骨魔，让他攻击一名玩家。", "reminders": ["死亡", "保留能力", "中毒"], "setup": true],
    ["id": "meiyoudashi11111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/no_dashii.png", "edition": "custom", "name": "诺-达鲺", "ability": "每个夜晚*，你要选择一名玩家：他死亡。与你邻近的两名镇民中毒。", "team": "demon", "sch_team": "恶魔", "firstNight": 0, "otherNight": 37, "firstNightReminder": "", "otherNightReminder": "唤醒诺-达鲺，让他攻击一名玩家。", "reminders": ["死亡", "中毒"], "setup": false],
    ["id": "fangguuuuuuuuuuuuuu111", "image": "https://oss.gstonegames.com/data_file/clocktower/web/icons/fang_gu.png", "edition": "custom", "name": "方古", "ability": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "team": "demon", "sch_team": "恶魔", "firstNight": 0, "otherNight": 36, "otherNightReminder": "唤醒方古，让他攻击一名玩家。如果该玩家是外来者并成功转化，则方古死亡，在他入睡后通知那名外来者角色变化。", "reminders": ["死亡", "限一次"], "setup": true],
    ["id": "13_meta", "image": "https://clocktower-wiki.gstonegames.com/images/thumb/d/de/Pithag.png/300px-Pithag.png", "name": "麻脸巫婆&落难少女", "team": "a jinxed", "setup": 0, "ability": "如果麻脸巫婆创造了落难少女，改为由说书人来决定哪一名玩家变成落难少女。"],
    ["id": "71_meta", "image": "https://clocktower-wiki.gstonegames.com/images/thumb/9/97/Fanggu.png/300px-Fanggu.png", "name": "方古&红唇女郎", "team": "a jinxed", "setup": 0, "ability": "如果方古成功转化了外来者并因此死去，红唇女郎不会变成方古。"],
    ["id": "1122000000222222222222222333_meta", "image": "https://clocktower-wiki.gstonegames.com/images/f/f1/Boffin.png", "name": "科学怪人&酒鬼", "team": "a jinxed", "setup": 0, "ability": "如果恶魔拥有酒鬼的能力，改为由科学怪人选择一名玩家：如果他是镇民，他醉酒。"]
]
